### ISSUE TITLE
When adding a ViewPager as header, the viewpager can not scroll smoothly.

### ISSUE THREAD

**Issue by lovetuzitong** [liaohuqiu/android-GridViewWithHeaderAndFooter#10]
As the title description. But when I add this head to an original ListView, it works perfect. So I think there is maybe something conflict between these two.

**Comment by liaohuqiu** [comment]
@lovetuzitong Why you close this issue?

**Comment by lovetuzitong** [comment]
Ah..I have solved this problem. The issue I opened before is not exactly, the problem is when I user `ViewPager.setCurrentItem(position, smooth)` the page scrolled without any animation.
In line 629 : 
``` java
if (position % mNumColumns == 0) {
    return headerViewContainer;
}
```
modified to : 
``` java
if ((position+1) % mNumColumns == 0) {
    return headerViewContainer;
}
```
Ensure the header view is at top level of this row.

**Comment by Jcdroid** [comment]
@lovetuzitong Thank u so much!:smile:

**Comment by Jcdroid** [comment]
@lovetuzitong
 I found a screen flicker problem when i use your method, and then add some code solved screen flicker problem.
```java
ViewPager viewPager = (ViewPager) headerViewContainer.findViewById(R.id.viewPager);
if (viewPager != null) {
      position++;
      headerViewContainer.setMinimumWidth(your phone screen width);
}
if (position % mNumColumns == 0) {
    return headerViewContainer;
}
```

**Comment by lovetuzitong** [comment]
@Jcdroid Good job !
