### ISSUE TITLE
Get original ListAdapter

### ISSUE THREAD

**Issue by pushbit** [liaohuqiu/android-GridViewWithHeaderAndFooter#11]
It would be nice to be able to get back the `ListAdapter` that we provide in `setAdapter`.  Currently we would have to use something like
`(SomeAdapter) ((WrapperListAdapter) getAdapter()).getWrappedAdapter()`
which is a bit long.  Maybe `GridViewWithHeaderAndFooter` could have a new method, `getListAdapter`.

**Comment by liaohuqiu** [comment]
`ListView` and `GridView` do not support that, do you think it's necessary?

**Comment by pushbit** [comment]
It's not necessary.  It would just be a convenience.

**Comment by liaohuqiu** [comment]
OK, I will add it. Thank you for your suggestion.
