### ISSUE TITLE
Getting wrong position of the clicked item?

### ISSUE THREAD

**Issue by ramswaroop** [liaohuqiu/android-GridViewWithHeaderAndFooter#14]
I have attached a click listener but getting incorrect position when a particular grid item is clicked. My code is as follows:
```java
mGridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Media media = mMedias.get(position);

                Intent i = new Intent(getActivity(), MediaDetailActivity.class);
                i.putExtra(MediaDetailFragment.EXTRA_MEDIA, media);
                startActivity(i);
            }
        });
```
Can you tell me where I am going wrong?

**Comment by liaohuqiu** [comment]
Try `id`.

**Comment by ramswaroop** [comment]
Yes, `id` works :)

But can you tell me why this happens so?

**Comment by liaohuqiu** [comment]
Like `ListView`, every sub view in `GirdView` is a Adapter View.  They are managed by a inner view adapter. When they are clicked, the click event will be processed by `OnItemClickListener`.  `position` is  indicate the position of the position of the view in the view adapter. If there is no header views. The `position` equals the position of the data which is related to the view in the data list.

```
/**
 * Interface definition for a callback to be invoked when an item in this
 * AdapterView has been clicked.
 */
public interface OnItemClickListener {

    /**
     * Callback method to be invoked when an item in this AdapterView has
     * been clicked.
     * <p>
     * Implementers can call getItemAtPosition(position) if they need
     * to access the data associated with the selected item.
     *
     * @param parent The AdapterView where the click happened.
     * @param view The view within the AdapterView that was clicked (this
     *            will be a view provided by the adapter)
     * @param position The position of the view in the adapter.
     * @param id The row id of the item that was clicked.
     */
    void onItemClick(AdapterView<?> parent, View view, int position, long id);
}
```

**Comment by PankovSerge** [comment]
Hello, liaohuqiu! I try to use id, but every time i got a 0. Position of selected item changed from device to device with change of columns count. 

@Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

        Log.d("DEBUG", "Selected item position " + position: + ", with id: " + id);
    }

Selected item with position 5, with id 0
 Selected item with position 6, with id 0
 Selected item with position 7, with id 0

**Comment by liaohuqiu** [comment]
@PankovSerge  sorry for replying so late. Is the `position` right?

**Comment by PankovSerge** [comment]
Got this issue when use header view. I use a custom adapter extended from BaseAdapter, and got it working by use id instead of position. 
```java
 @Override
    public long getItemId(int position) {
        return position;
    }
```

One more problem with onClick Handler, if you don't setup it like that 
```java
   footerView.setOnClickListener(this);
    }
```
you have got error in 
```java
@Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
    }
```
because footerView have position > yourSource.size().  Need to add this moments to README.
