### ISSUE TITLE
Android 2.3.7 NoSuchFiledException:mColumnWidth

### ISSUE THREAD

**Issue by xufan** [liaohuqiu/android-GridViewWithHeaderAndFooter#21]
03-04 02:25:06.840: E/AndroidRuntime(625): FATAL EXCEPTION: main
03-04 02:25:06.840: E/AndroidRuntime(625): java.lang.RuntimeException: java.lang.NoSuchFieldException: mColumnWidth
03-04 02:25:06.840: E/AndroidRuntime(625): 	at com.huaban.android.ui.view.HeaderFooterGridView.getColumnWidthCompatible(HeaderFooterGridView.java:308)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at com.huaban.android.ui.view.HeaderFooterGridView.getRowHeight(HeaderFooterGridView.java:337)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at com.huaban.android.ui.view.HeaderFooterGridView.onMeasure(HeaderFooterGridView.java:106)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:701)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:311)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.support.v4.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:559)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1456)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:581)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:365)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1456)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1017)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:386)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:309)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.View.measure(View.java:8313)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewRoot.performTraversals(ViewRoot.java:839)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.os.Looper.loop(Looper.java:130)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at android.app.ActivityThread.main(ActivityThread.java:3683)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at java.lang.reflect.Method.invoke(Method.java:507)
03-04 02:25:06.840: E/AndroidRuntime(625): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCall

**Comment by liaohuqiu** [comment]
Thank you for you feedback +1

**Comment by comtaler** [comment]
Can you make a new release with this fix? I have a project that depends on this lib. Thanks.

**Comment by liaohuqiu** [comment]
1.0.10 has been released.
