### ISSUE TITLE
android 2.3.3 getClass().getSuperclass().getDeclaredField("mColumnWidth")

### ISSUE THREAD

**Issue by McGars** [liaohuqiu/android-GridViewWithHeaderAndFooter#23]
Hi! Crush on  android 2.3.+
can you change
Field numColumns = getClass().getSuperclass().getDeclaredField("mColumnWidth");
on
Field numColumns = GridView.class.getDeclaredField("mColumnWidth");

**Comment by liaohuqiu** [comment]
It's fixed now. And I've published the snapshot version: `1.0.10.1-SNAPSHOT` to 

https://oss.sonatype.org/content/repositories/snapshots/

If it works well, I will publish the release version at once.
