### ISSUE TITLE
Dublicate icon

### ISSUE THREAD

**Issue by AlekseiMDG** [liaohuqiu/android-GridViewWithHeaderAndFooter#26]
I choose some position in goods, and when i scrolling down and late scroll up, I return on position i see dublicate icon checket goods. i use verion library 1.0.11
![issues](https://cloud.githubusercontent.com/assets/4759824/7608146/51bd3402-f980-11e4-90a9-6ae9dd72e15e.png)

**Comment by liaohuqiu** [comment]
I think it's issue related view holder in AbsListView. You can change GridViewWithHeaderAndFooter to GridView to check this issue.
