### ISSUE TITLE
setEmptyView don't work when use addFooterView

### ISSUE THREAD

**Issue by PankovSerge** [liaohuqiu/android-GridViewWithHeaderAndFooter#27]
Empty view not showing if you use addFooter view, no exceptions.

**Comment by PankovSerge** [comment]
Add emptyView use a isEmpty() adapter method. When we add footer, that method don't return true, so solution is: 

@Override
             public boolean isEmpty() {
   //        boolean empty = (mAdapter == null || mAdapter.isEmpty()) && getHeadersCount() == 0 && getFootersCount() == 0;
              boolean empty = (mAdapter == null || mAdapter.isEmpty());
              return empty;
             }

**Comment by liaohuqiu** [comment]
:+1:  thank you.
