### ISSUE TITLE
添加多个header后,header之间会出现一个间隔

### ISSUE THREAD

**Issue by litao0621** [liaohuqiu/android-GridViewWithHeaderAndFooter#29]
比如添加3个header后，12之间，23之间会存在一个间隔，看了下，感觉和 #8 描述的有点像。

**Comment by liaohuqiu** [comment]
divider 去掉看看？

**Comment by litao0621** [comment]
就像这样，我去掉divider先试下
![Image](http://imglf1.ph.126.net/bLt-13wPcPDmVe89GOSDzg==/6608842237655637115.png)

**Comment by litao0621** [comment]
看了下代码，还是不太清除在哪里可以去掉divider，希望简单说明下，谢谢 :smile:

**Comment by liaohuqiu** [comment]
GridView 的 divider 设置为 null。群里有人遇到这个情况，他们是这样弄的。

**Comment by litao0621** [comment]
GridView没有提供设置divider的方法吧？我尝试在xml中加，但不起作用
<in.srain.cube.GridViewWithHeaderAndFooter
                android:id="@+id/load_more_grid_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fadingEdge="none"
                android:focusable="false"
                android:horizontalSpacing="@dimen/space3"
                android:verticalSpacing="@dimen/space3"
                android:listSelector="@android:color/transparent"
                android:divider="@null"
                android:numColumns="2"
                android:scrollbarStyle="outsideOverlay"
                android:stretchMode="columnWidth" />

**Comment by liaohuqiu** [comment]
开发者选项中的 LayoutBounds 打开，我看看这个是哪来的。

**Comment by litao0621** [comment]
.

**Comment by liaohuqiu** [comment]
`android:verticalSpacing="@dimen/space3"` 这个吧？

**Comment by litao0621** [comment]
确实是这个原因，谢谢，还有个问题想请教下，android:verticalSpacing应该只是给列表设置间距吧，我不想将这个属性附加到header上，我看了代码也但不明白原因，不知道你还有什么好得方法吗？

**Comment by liaohuqiu** [comment]
HeaderView 其实是 GridView 的一行伪装的。后面的几项都隐藏了。所有没有办法使用 `android:verticalSpacing`，我的做法是每一项的底部留白。

**Comment by litao0621** [comment]
好的，很不错，你真厉害， :+1:

**Comment by liaohuqiu** [comment]
过奖了。 :)
